language: php
dist: bionic
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - vendor

matrix:
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - ./vendor/bin/test-reporter
